### PR TITLE
 Refactor test client to remove globals

### PR DESCRIPTION
**Pull request by Urth**
So the repository link does not include the selected branch so I completely missed I was working on main instead of wip....

### CODE REVIEW

**Comment by wdoekes** [comment]
Same here. Conflicts, conflicts, conflicts :P

**Comment by Urth** [comment]
Hey flapdrol, al dat werk voor niks! 😭

**Comment by wdoekes** [comment]
Sad times :1st_place_medal:

**Comment by wdoekes** [comment]
Maaar.. hij is nu wel asyncio zoals ie had moeten zijn from the start.

Ik liep eerst lang tegen deze aan:
https://wjd.nu/notes/2022#curious-termios-error-switching-to-asyncio-serial

**Pull request closed without merging**
